#if !canImport(ObjectiveC)
import XCTest

extension swiftMetalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__swiftMetalTests = [
        ("testMetalCreateSystemDefaultDevice", testMetalCreateSystemDefaultDevice),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(swiftMetalTests.__allTests__swiftMetalTests),
    ]
}
#endif
